apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tftcsgqn1-python
  janus-idp.io/tekton: tftcsgqn1-python
  backstage.io/kubernetes-id: tftcsgqn1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tftcsgqn1-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
